topics = [
    # Original Topics
    "Quantum Computing",
    "Machine Learning",
    "Blockchain Technology",
    "Renewable Energy",
    "Genetic Engineering",
    "Artificial Intelligence",
    "Climate Change",
    "Cybersecurity",
    "Virtual Reality",
    "Space Exploration",

    # Added Topics (150+)

    # Science & Technology (Expanded)
    "Nanotechnology",
    "Biotechnology",
    "Robotics",
    "3D Printing",
    "Augmented Reality",
    "Internet of Things (IoT)",
    "Big Data Analytics",
    "Cloud Computing",
    "5G and 6G Technology",
    "Autonomous Vehicles",
    "Material Science",
    "Aerospace Engineering",
    "Bioinformatics",
    "Neuroscience",
    "Particle Physics",
    "Astrophysics",
    "Oceanography",
    "Geology",
    "Meteorology",
    "Seismology",
    "Volcanology",
    "Cryptography",
    "Edge Computing",
    "Quantum Mechanics",
    "Quantum Sensors",
    "Fusion Energy",
    "Synthetic Biology",
    "Wearable Technology",
    "Drone Technology",
    "FinTech (Financial Technology)",

    # Health & Medicine
    "Immunology",
    "Virology",
    "Epidemiology",
    "Public Health",
    "Mental Health",
    "Cardiology",
    "Oncology",
    "Neurology",
    "Pharmacology",
    "Personalized Medicine",
    "Telemedicine",
    "Medical Imaging",
    "Drug Discovery",
    "Vaccine Development",
    "Nutrition Science",
    "Aging Research (Gerontology)",
    "Microbiome Research",
    "Regenerative Medicine",
    "Healthcare Systems",
    "Global Health Initiatives",
    "Antibiotic Resistance",
    "Chronic Diseases Management",
    "Exercise Physiology",
    "Sleep Science",

    # Environment & Sustainability
    "Biodiversity Conservation",
    "Deforestation",
    "Water Scarcity and Management",
    "Pollution Control (Air, Water, Soil)",
    "Waste Management and Recycling",
    "Circular Economy",
    "Sustainable Agriculture",
    "Ocean Acidification",
    "Coral Reef Bleaching",
    "Wildlife Conservation",
    "Environmental Policy and Law",
    "Climate Modeling",
    "Carbon Capture and Storage",
    "Green Architecture",
    "Ecosystem Restoration",
    "Sustainable Transportation",
    "Light Pollution",
    "Soil Health",

    # Social Sciences & Humanities
    "Psychology (Cognitive, Social, Developmental)",
    "Sociology",
    "Anthropology",
    "Archaeology",
    "History (Ancient, Medieval, Modern)",
    "Philosophy (Ethics, Epistemology, Metaphysics)",
    "Political Science",
    "International Relations",
    "Economics (Macro, Micro, Behavioral)",
    "Linguistics",
    "Literature (Classical, Contemporary, World)",
    "Art History",
    "Music History and Theory",
    "Religious Studies",
    "Cultural Studies",
    "Gender Studies",
    "Urban Studies",
    "Geopolitics",
    "Human Rights",
    "Public Policy Analysis",
    "Criminology",
    "Education Theory and Practice",

    # Business & Economics
    "Supply Chain Management",
    "Digital Marketing",
    "E-commerce",
    "Entrepreneurship",
    "Venture Capital",
    "Stock Market Analysis",
    "International Business",
    "Corporate Social Responsibility (CSR)",
    "Organizational Behavior",
    "Leadership Studies",
    "Project Management",
    "Risk Management",
    "Behavioral Economics",
    "Game Theory",
    "Development Economics",
    "Global Trade",

    # Arts, Culture & Lifestyle
    "Film Studies",
    "Photography",
    "Graphic Design",
    "Architecture",
    "Culinary Arts",
    "World Cuisines",
    "Fashion History and Design",
    "Performing Arts (Theatre, Dance)",
    "Mythology",
    "Folklore",
    "Digital Art",
    "Animation",
    "Museum Studies",
    "Travel and Tourism",
    "Minimalism",
    "Urban Planning",

    # Hobbies & Recreation
    "Gardening and Horticulture",
    "Astronomy (Amateur)",
    "Chess Strategy",
    "Board Games and Tabletop RPGs",
    "Video Game Development",
    "Esports",
    "Hiking and Mountaineering",
    "DIY and Crafting",
    "Creative Writing",
    "Musical Instrument Performance",
    "Home Brewing/Winemaking",
    "Yoga and Meditation",

    # Other/Interdisciplinary
    "Data Visualization",
    "Information Theory",
    "Systems Thinking",
    "Futures Studies / Futurology",
    "Disaster Preparedness and Response",
    "Forensic Science",
    "Animal Behavior (Ethology)",
    "Science Communication",
    "Intellectual Property Law",
    "Media Studies",
    "Fake News and Disinformation",
    "Digital Ethics",
    "Human-Computer Interaction (HCI)",
    "Memory Studies",
    "Peace and Conflict Studies"
]

# Optional: Print the number of topics to verify
# print(f"Total number of topics: {len(topics)}")